---
apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    name: server
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
  containers:
    - name: server
      image: docker.io/piotr439/https-server:latest
      ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort # or LoadBalancer if you're in a cloud environment
  selector:
    name: server
  ports:
    - name: https
      protocol: TCP
      port: 443 # Expose service on port 443 (HTTPS default)
      targetPort: 3000 # Forward traffic to container's port 3000
      nodePort: 30001 # Optional, the NodePort for external access

